import convergence_absolute_convergence_fourier_trigonometric_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace convergence_absolute_convergence_fourier_trigonometric_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end convergence_absolute_convergence_fourier_trigonometric_theorem_canonical_lane_mathlib
end HautevilleHouse
